import type { TourEvent } from "@/types/events";

export const tourEvents: readonly TourEvent[] = [
  {
    id: "evt-001",
    date: "2026-09-18",
    time: "23:00",
    venue: "Demo Kraftwerk Vault",
    city: "Demo City",
    country: "Germany",
    eventName: "Resonance Night 01",
    status: "confirmed",
    ticketUrl: "https://example.com/tickets/demo-event-1",
    timeframe: "upcoming",
  },
  {
    id: "evt-002",
    date: "2026-10-02",
    time: "01:00",
    venue: "Demo Concrete Bunker",
    city: "Demo Metropolis",
    country: "Netherlands",
    eventName: "Sub-Sonic Sessions",
    status: "confirmed",
    ticketUrl: "https://example.com/tickets/demo-event-2",
    timeframe: "upcoming",
  },
  {
    id: "evt-003",
    date: "2026-10-24",
    time: "02:30",
    venue: "Demo Warehouse 84",
    city: "Demo Capital",
    country: "United Kingdom",
    eventName: "Monolith Showcase",
    status: "sold-out",
    ticketUrl: "https://example.com/tickets/demo-event-3",
    timeframe: "upcoming",
  },
  {
    id: "evt-004",
    date: "2026-11-07",
    time: "23:30",
    venue: "Demo Silo Hall",
    city: "Demo Port",
    country: "Belgium",
    eventName: "Industrial Kinetics",
    status: "confirmed",
    ticketUrl: "https://example.com/tickets/demo-event-4",
    timeframe: "upcoming",
  },
  {
    id: "evt-005",
    date: "2026-06-12",
    venue: "Demo Open Air Grounds",
    city: "Demo City",
    country: "Germany",
    eventName: "Circuit Solstice Festival",
    status: "confirmed",
    timeframe: "past",
  },
  {
    id: "evt-006",
    date: "2026-04-05",
    venue: "Demo Underground Tunnel",
    city: "Demo Metropolis",
    country: "France",
    eventName: "Dark Horizon Series",
    status: "sold-out",
    timeframe: "past",
  },
  {
    id: "evt-007",
    date: "2026-01-20",
    venue: "Demo Industrial Hangar",
    city: "Demo Nord",
    country: "Sweden",
    eventName: "Subzero Winter Assembly",
    status: "confirmed",
    timeframe: "past",
  },
];
