import type { GalleryImage } from "@/types/gallery";

export const galleryImages: readonly GalleryImage[] = [
  {
    id: "gal-001",
    src: "/images/gallery/demo-gallery-1.jpg",
    alt: "DEMO ARTIST performing live in dark warehouse setting with red signal lights",
    width: 1200,
    height: 800,
    aspectRatio: "3:2",
    category: "live",
    priority: true,
  },
  {
    id: "gal-002",
    src: "/images/gallery/demo-gallery-2.jpg",
    alt: "Modular synthesizer hardware and patch cables in dimly lit demo studio",
    width: 1200,
    height: 900,
    aspectRatio: "4:3",
    category: "studio",
    priority: false,
  },
  {
    id: "gal-003",
    src: "/images/gallery/demo-gallery-3.jpg",
    alt: "Silhouette of DEMO ARTIST behind CDJs with strobe lighting effect",
    width: 1200,
    height: 675,
    aspectRatio: "16:9",
    category: "live",
    priority: true,
  },
  {
    id: "gal-004",
    src: "/images/gallery/demo-gallery-4.jpg",
    alt: "Monochromatic editorial portrait of DEMO ARTIST in industrial architecture",
    width: 800,
    height: 1000,
    aspectRatio: "4:5",
    category: "editorial",
    priority: false,
  },
  {
    id: "gal-005",
    src: "/images/gallery/demo-gallery-5.jpg",
    alt: "Analog turntable platter spinning 12-inch demo test pressing",
    width: 1000,
    height: 1000,
    aspectRatio: "1:1",
    category: "press",
    priority: false,
  },
  {
    id: "gal-006",
    src: "/images/gallery/demo-gallery-6.jpg",
    alt: "Audience crowd in dense fog at underground techno showcase",
    width: 1200,
    height: 800,
    aspectRatio: "3:2",
    category: "live",
    priority: false,
  },
];
